---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keyval-collector
  namespace: {{ .Release.Namespace }}
  annotations:
    keyval.dev/skip: "true"
  labels:
    app: keyval-collector
    component: keyval-collector
spec:
  selector:
    matchLabels:
      app: keyval-collector
      component: keyval-collector
  minReadySeconds: 5
  progressDeadlineSeconds: 120
  replicas: 1
  template:
    metadata:
      labels:
        app: keyval-collector
        component: keyval-collector
    spec:
      containers:
        - command:
            - "/otelcontribcol"
            - "--config=/conf/collector-conf.yaml"
          image: "{{ .Values.collector.image.repository }}:{{ .Values.collector.image.tag }}"
          name: collector
          resources:
            limits:
              cpu: 1
              memory: 2Gi
            requests:
              cpu: 200m
              memory: 400Mi
          ports:
            - containerPort: 55679 # Default endpoint for ZPages.
            - containerPort: 4317 # Default endpoint for OpenTelemetry receiver.
            - containerPort: 14250 # Default endpoint for Jaeger HTTP receiver.
            - containerPort: 14268 # Default endpoint for Jaeger HTTP receiver.
            - containerPort: 9411 # Default endpoint for Zipkin receiver.
            - containerPort: 8888 # Default endpoint for querying metrics.
          volumeMounts:
            - name: collector-config-vol
              mountPath: /conf
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: 13133 # Health Check extension default port.
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: 13133 # Health Check extension default port.
      volumes:
        - configMap:
            name: collector-conf
            items:
              - key: collector-conf
                path: collector-conf.yaml
          name: collector-config-vol
