apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: keyval-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: keyval-proxy-role
subjects:
- kind: ServiceAccount
  name: keyval-controller-manager
  namespace: {{ .Release.Namespace }}
