---
apiVersion: v1
kind: Service
metadata:
  name: collector
  namespace: {{ .Release.Namespace }}
  labels:
    app: keyval-collector
    component: keyval-collector
spec:
  ports:
    - name: otlp # Default endpoint for OpenTelemetry receiver.
      port: 55680
      protocol: TCP
      targetPort: 55680
    - name: zipkin # Default endpoint for Zipkin receiver.
      port: 9411
      protocol: TCP
      targetPort: 9411
    - name: metrics # Default endpoint for querying metrics.
      port: 8888
  selector:
    component: keyval-collector