apiVersion: v1
data:
  api_key: "{{ .Values.keyval.apikey }}"
  controller_manager_config.yaml: |
    apiVersion: controller-runtime.sigs.k8s.io/v1alpha1
    kind: ControllerManagerConfig
    health:
      healthProbeBindAddress: :8081
    metrics:
      bindAddress: 127.0.0.1:8080
    webhook:
      port: 9443
    leaderElection:
      leaderElect: true
      resourceName: 9e75379c.keyval.dev
kind: ConfigMap
metadata:
  name: keyval-manager-config
  namespace: {{ .Release.Namespace }}
