apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-manager
  name: keyval-controller
  namespace: keyval-system
spec:
  ports:
  - name: http
    port: 9080
    targetPort: 9080
  selector:
    control-plane: controller-manager
